### ISSUE TITLE
Errores y confusiones

### ISSUE THREAD

**Issue by nanmon** [IA-UNISON/tarea03-SatisfaccionRestricciones#9]
En el archivo Sudoku.py se llama a la función csp.solucion_CSP_bin que no existe.

La función consistencia no se entiende que debe devolver

**Comment by juliowaissman** [comment]
Ups, creo que ya corregí ese y otros errores más. Muchas gracias!!!!

Du¡isculpa no haber contestado en el momento que resolví el issue.
